SkillSphere-.NET/SkillSphere/Areas/Admin/Controllers/ConsultationController.cs
using Microsoft.AspNetCore.Mvc;
using SkillSphere.DataAccess.Repository.IRepository;
using SkillSphere.Models;

namespace SkillSphere.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class ConsultationController : Controller
    {
        private readonly IConsultationRepository _consultationRepository;

        public ConsultationController(IConsultationRepository consultationRepository)
        {
            _consultationRepository = consultationRepository;
        }

        // GET: Consultation
        public IActionResult Index()
        {
            var consultations = _consultationRepository.GetAllConsultations();
            return View(consultations);
        }

        // GET: Consultation/Details/5
        public IActionResult Details(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }
            return View(consultation);
        }

        // GET: Consultation/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Consultation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Title,Description,Duration,CallPlatform,ExternalLink,Price,StartDate")] Consultation consultation)
        {
            if (ModelState.IsValid)
            {
                _consultationRepository.AddConsultation(consultation);
                _consultationRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(consultation);
        }

        // GET: Consultation/Edit/5
        public IActionResult Edit(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }
            return View(consultation);
        }

        // POST: Consultation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Title,Description,Duration,CallPlatform,ExternalLink,Price,StartDate")] Consultation consultation)
        {
            if (id != consultation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _consultationRepository.UpdateConsultation(consultation);
                _consultationRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(consultation);
        }

        // GET: Consultation/Delete/5
        public IActionResult Delete(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }
            return View(consultation);
        }

        // POST: Consultation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _consultationRepository.DeleteConsultation(id);
            _consultationRepository.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

SkillSphere-.NET/SkillSphere/Areas/Admin/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillSphere.Models;
using SkillSphere.Repositories;
using SkillSphere.Utility;
using System.Security.Claims;

namespace SkillSphere.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;

        public CourseController(ICourseRepository courseRepository)
        {
            _courseRepository = courseRepository;
        }

        // GET: Course
        public IActionResult Index()
        {
            var courses = _courseRepository.GetAllCourses();
            return View(courses);
        }

        // GET: Course/Details/5
        public IActionResult Details(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // GET: Course/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
      
        public IActionResult Create([Bind("Title,Description,Price,VideoUrl")] Course course)
        {
            if (ModelState.IsValid)
            {
                

                _courseRepository.AddCourse(course);
                _courseRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }


        // GET: Course/Edit/5
        public IActionResult Edit(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Course/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Title,Description,Price,VideoUrl")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _courseRepository.UpdateCourse(course);
                _courseRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Course/Delete/5
        public IActionResult Delete(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }


        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                _courseRepository.DeleteCourse(id);
                _courseRepository.Save();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Log the exception or handle it accordingly
                return StatusCode(500, "Internal server error");
            }
        }

    }
}

SkillSphere-.NET/SkillSphere/Areas/Customer/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillSphere.DataAccess.Data;
using SkillSphere.DataAccess.Repository.IRepository;
using SkillSphere.Repositories;
using SkillSphere.Utility;
using System.Security.Claims;
using SkillSphere.Models.ViewModels;
using SkillSphere.Models;


namespace SkillSphere.Areas.Customer.Controllers
{
    
    [Area("Customer")]
    public class UserController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IConsultationRepository _consultationRepository;
        private readonly ApplicationDbContext _context;
             private readonly IConfiguration _configuration;

        public UserController(ICourseRepository courseRepository, IConsultationRepository consultationRepository, ApplicationDbContext context, IConfiguration configuration)
        {
            _courseRepository = courseRepository;
            _consultationRepository = consultationRepository;
            _context = context;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var courses = _courseRepository.GetAllCourses().ToList();
            var consultations = _consultationRepository.GetAllConsultations().ToList();

            // Log the count of courses and consultations
            Console.WriteLine($"Courses Count: {courses.Count}");
            Console.WriteLine($"Consultations Count: {consultations.Count}");

            var viewModel = new UserDashboardViewModel
            {
                Courses = courses,
                Consultations = consultations
            };

            return View(viewModel);
        }

        [Authorize(Roles = SD.Role_Customer)]
        public IActionResult PurchaseCourse(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }

            // Logic to add course to the user's list
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userCourse = new UserCourse
            {
                CourseId = course.Id,
                UserId = userId
            };
            _context.UserCourses.Add(userCourse);
            _context.SaveChanges();

            return RedirectToAction("MyCourses");
        }

        [Authorize(Roles = SD.Role_Customer)]
        public IActionResult PurchaseConsultation(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }

            // Logic to add consultation to the user's list
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userConsultation = new UserConsultation
            {
                ConsultationId = consultation.Id,
                UserId = userId
            };
            _context.UserConsultations.Add(userConsultation);
            _context.SaveChanges();

            return RedirectToAction("MyConsultations");
        }

        [Authorize(Roles = SD.Role_Customer)]
        [Route("Customer/User/MyCourse")]
        public IActionResult MyCourses()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var courses = _context.UserCourses
                                  .Where(uc => uc.UserId == userId)
                                  .Select(uc => uc.Course)
                                  .ToList();
            return View(courses);
        }

        [Authorize(Roles = SD.Role_Customer)]
        [Route("Customer/User/MyConsultation")]
        public IActionResult MyConsultations()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var consultations = _context.UserConsultations
                                        .Where(uc => uc.UserId == userId)
                                        .Select(uc => uc.Consultation)
                                        .ToList();
            return View(consultations);
        }


        [Route("Customer/User/CourseDetails/{id}")]
        public IActionResult CourseDetails(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewBag.PaypalClientId = _configuration["PaypalSettings:ClientId"];
            ViewBag.PaypalSecret = _configuration["PaypalSettings:Secret"];
            ViewBag.PaypalUrl = _configuration["PaypalSettings:Url"];
            return View(course);
        }

        [Route("Customer/User/ConsultationDetails/{id}")]
        public IActionResult ConsultationDetails(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }
            ViewBag.PaypalClientId = _configuration["PaypalSettings:ClientId"];
            ViewBag.PaypalSecret = _configuration["PaypalSettings:Secret"];
            ViewBag.PaypalUrl = _configuration["PaypalSettings:Url"];
            return View(consultation);
        }

        //[Authorize(Roles = SD.Role_Customer)]
       
        //public async Task<IActionResult> AddToCalendar(int id)
        //{
        //    var consultation = _consultationRepository.GetConsultationById(id);
        //    if (consultation == null)
        //    {
        //        return NotFound();
        //    }

        //    var googleAuth = _configuration.GetSection("GoogleAuth");
        //    string[] scopes = { CalendarService.Scope.Calendar };

        //    var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
        //        new ClientSecrets
        //        {
        //            ClientId = googleAuth["ClientId"],
        //            ClientSecret = googleAuth["ClientSecret"]
        //        },
        //        scopes,
        //        "user",
        //        CancellationToken.None);

        //    var service = new CalendarService(new BaseClientService.Initializer()
        //    {
        //        HttpClientInitializer = credential,
        //        ApplicationName = "SkillSphere",
        //    });

        //    var calendarEvent = new Event
        //    {
        //        Summary = consultation.Title,
        //        Description = consultation.Description,
        //        Start = new EventDateTime
        //        {
        //            DateTime = consultation.StartDate,
        //            TimeZone = "Asia/Kolkata"
        //        },
        //        End = new EventDateTime
        //        {
        //            DateTime = consultation.EndDate,
        //            TimeZone = "Asia/Kolkata"
        //        },
        //        Attendees = new List<EventAttendee>
        //    {
        //        new EventAttendee { Email = "attendee@example.com" }
        //    },
        //        ConferenceData = new ConferenceData
        //        {
        //            CreateRequest = new CreateConferenceRequest
        //            {
        //                RequestId = Guid.NewGuid().ToString(),
        //                ConferenceSolutionKey = new ConferenceSolutionKey
        //                {
        //                    Type = "hangoutsMeet"
        //                }
        //            }
        //        }
        //    };

        //    var request = service.Events.Insert(calendarEvent, "primary");
        //    request.ConferenceDataVersion = 1;
        //    var createdEvent = await request.ExecuteAsync();

        //    return Redirect(createdEvent.HtmlLink);
        //}

        //[Authorize(Roles = SD.Role_Customer)]
        //public async Task<IActionResult> AuthorizeGoogleCalendar(int id)
        //{
        //    var googleAuth = _configuration.GetSection("GoogleAuth");
        //    string[] scopes = { CalendarService.Scope.Calendar };

        //    var redirectUri = Url.Action("GoogleCalendarCallback", "User", new { id }, Request.Scheme);

        //    var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
        //        new ClientSecrets
        //        {
        //            ClientId = googleAuth["ClientId"],
        //            ClientSecret = googleAuth["ClientSecret"]
        //        },
        //        scopes,
        //        "user",
        //        CancellationToken.None,
        //        new FileDataStore("Google.Apis.Auth")
        //    );

        //    if (credential.Token.IsExpired(credential.Flow.Clock))
        //    {
        //        if (await credential.RefreshTokenAsync(CancellationToken.None))
        //        {
        //            // Redirect to the callback with the consultation ID
        //            return RedirectToAction("GoogleCalendarCallback", new { id });
        //        }
        //    }

        //    // If already authorized, redirect to callback immediately
        //    return RedirectToAction("GoogleCalendarCallback", new { id });
        //}



        //[Authorize(Roles = SD.Role_Customer)]
        //[Route("Customer/User/GoogleCalendarCallback")]
        //public async Task<IActionResult> GoogleCalendarCallback(int id)
        //{
        //    var consultation = _consultationRepository.GetConsultationById(id);
        //    if (consultation == null)
        //    {
        //        return NotFound();
        //    }

        //    var googleAuth = _configuration.GetSection("GoogleAuth");
        //    string[] scopes = { CalendarService.Scope.Calendar };

        //    var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
        //        new ClientSecrets
        //        {
        //            ClientId = googleAuth["ClientId"],
        //            ClientSecret = googleAuth["ClientSecret"]
        //        },
        //        scopes,

SkillSphere-.NET/SkillSphere/Views/Shared/_Layout.cshtml
@using SkillSphere.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SkillSphere</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SkillSphere.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="User" asp-action="Index">
                    <img src="/images/Logo.png" alt="SkillSphere Logo" style="height: 45px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between me-auto">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="User" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>  
                        
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Course" asp-action="Index">Courses</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Consultation" asp-action="Index">Workshops</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Customer))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Bagpack
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Customer" asp-controller="User" asp-action="MyCourses">My Learnings</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Customer" asp-controller="User" asp-action="MyConsultation">My Workshops</a>
                                    </li>
                                   
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"/> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-light">
        <div class="container">
            &copy; 2024 - <i class="bi bi-film"></i> SkillSphere <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.tiny.cloud/1/4bdmeb9rspr0fo73ayz1gggbzy9eri4lp57hcyba1ivbh84d/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/2.0.8/js/dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- FullCalendar CSS -->
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.7/dist/fullcalendar.min.css' rel='stylesheet' />

    <!-- FullCalendar JS -->
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.7/dist/fullcalendar.min.js'></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

            

SkillSphere-.NET/SkillSphere/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
   
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}