SkillSphere-.NET/SkillSphere/Areas/Customer/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillSphere.Utility;
using System.Text;
using System.Text.Json.Nodes;

namespace SkillSphere.Areas.Customer.Controllers
{
    [Authorize(Roles = SD.Role_Customer)]
    [Area("Customer")]
    public class CheckoutController : Controller
    {
        private string PaypalClientId { get; set; } = "";
        private string PaypalSecret { get; set; } = "";
        private string PaypalUrl { get; set; } = "";

        public CheckoutController(IConfiguration configuration)
        {
            PaypalClientId = configuration["PaypalSettings:ClientId"]!;
            PaypalSecret = configuration["PaypalSettings:Secret"]!;
            PaypalUrl = configuration["PaypalSettings:Url"]!;
        }
        public IActionResult IndexCourse()
        {
            ViewBag.PaypalClientId = PaypalClientId;
            return View();
        }

        public IActionResult IndexConsultation()
        {
            ViewBag.PaypalClientId = PaypalClientId;
            return View();
        }



        [HttpPost]
        public async Task<JsonResult> CreateOrder([FromBody] JsonObject data)
        {
            var totalAmount = data["amount"]?.ToString();
            if (totalAmount == null)
            {
                return new JsonResult(new { Id = "" });
            }

            // create the request body
            JsonObject createOrderRequest = new JsonObject();
            createOrderRequest.Add("intent", "CAPTURE");

            JsonObject amount = new JsonObject();
            amount.Add("currency_code", "USD");
            amount.Add("value", totalAmount);

            JsonObject purchaseUnit1 = new JsonObject();
            purchaseUnit1.Add("amount", amount);

            JsonArray purchaseUnits = new JsonArray();
            purchaseUnits.Add(purchaseUnit1);


            createOrderRequest.Add("purchase_units", purchaseUnits);

            // get access token
            string accessToken = await GetPaypalAccessToken();

            // send request
            string url = PaypalUrl + "/v2/checkout/orders";


            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + accessToken);

                var requestMessage = new HttpRequestMessage(HttpMethod.Post, url);
                requestMessage.Content = new StringContent(createOrderRequest.ToString(), null, "application/json");
                var httpResponse = await client.SendAsync(requestMessage);

                if (httpResponse.IsSuccessStatusCode)
                {
                    var strResponse = await httpResponse.Content.ReadAsStringAsync();
                    var jsonResponse = JsonNode.Parse(strResponse);

                    if (jsonResponse != null)
                    {
                        string paypalOrderId = jsonResponse["id"]?.ToString() ?? "";
                        return new JsonResult(new { Id = paypalOrderId });
                    }
                }

            }




            return new JsonResult(new { Id = "" });
        }


        [HttpPost]
        public async Task<JsonResult> CompleteOrder([FromBody] JsonObject data)
        {
            var orderId = data?["orderID"]?.ToString();
            if (orderId == null)
            {
                return new JsonResult("error");
            }

            // get access token
            string accessToken = await GetPaypalAccessToken();

            string url = PaypalUrl + "/v2/checkout/orders/" + orderId + "/capture";

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + accessToken);

                var requestMessage = new HttpRequestMessage(HttpMethod.Post, url);
                requestMessage.Content = new StringContent("{ }", null, "application/json");

                var httpResponse = await client.SendAsync(requestMessage);

                if (httpResponse.IsSuccessStatusCode)
                {
                    var strResponse = await httpResponse.Content.ReadAsStringAsync();
                    var jsonResponse = JsonNode.Parse(strResponse);

                    if (jsonResponse != null)
                    {
                        string paypalOrderStatus = jsonResponse["status"]?.ToString() ?? "";
                        if (paypalOrderStatus == "COMPLETED")
                        {
                            // save the order in the database
                            return Json(new { status = "success" });
                        }
                    }
                }

            }





            return new JsonResult("error");
        }





        

        private async Task<string> GetPaypalAccessToken()
        {
            string accessToken = "";

            string url = PaypalUrl + "/v1/oauth2/token";

            using (var client = new HttpClient())
            {
                string credentials64 =
                    Convert.ToBase64String(Encoding.UTF8.GetBytes(PaypalClientId + ":" + PaypalSecret));

                client.DefaultRequestHeaders.Add("Authorization", "Basic " + credentials64);

                var requestMessage = new HttpRequestMessage(HttpMethod.Post, url);
                requestMessage.Content = new StringContent("grant_type=client_credentials", null
                    , "application/x-www-form-urlencoded");

                var httpResponse = await client.SendAsync(requestMessage);

                if (httpResponse.IsSuccessStatusCode)
                {
                    var strResponse = await httpResponse.Content.ReadAsStringAsync();
                    var jsonResponse = JsonNode.Parse(strResponse);

                    if (jsonResponse != null)
                    {
                        accessToken = jsonResponse["access_token"]?.ToString() ?? "";
                    }
                }
            }


            return accessToken;
        }



    }
}

SkillSphere-.NET/SkillSphere/Areas/Customer/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillSphere.DataAccess.Data;
using SkillSphere.DataAccess.Repository.IRepository;
using SkillSphere.Repositories;
using SkillSphere.Utility;
using System.Security.Claims;
using SkillSphere.Models.ViewModels;
using SkillSphere.Models;


namespace SkillSphere.Areas.Customer.Controllers
{
    
    [Area("Customer")]
    public class UserController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IConsultationRepository _consultationRepository;
        private readonly ApplicationDbContext _context;
             private readonly IConfiguration _configuration;

        public UserController(ICourseRepository courseRepository, IConsultationRepository consultationRepository, ApplicationDbContext context, IConfiguration configuration)
        {
            _courseRepository = courseRepository;
            _consultationRepository = consultationRepository;
            _context = context;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var courses = _courseRepository.GetAllCourses().ToList();
            var consultations = _consultationRepository.GetAllConsultations().ToList();

            // Log the count of courses and consultations
            Console.WriteLine($"Courses Count: {courses.Count}");
            Console.WriteLine($"Consultations Count: {consultations.Count}");

            var viewModel = new UserDashboardViewModel
            {
                Courses = courses,
                Consultations = consultations
            };

            return View(viewModel);
        }

        [Authorize(Roles = SD.Role_Customer)]
        public IActionResult PurchaseCourse(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }

            // Logic to add course to the user's list
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userCourse = new UserCourse
            {
                CourseId = course.Id,
                UserId = userId
            };
            _context.UserCourses.Add(userCourse);
            _context.SaveChanges();

            return RedirectToAction("MyCourses");
        }

        [Authorize(Roles = SD.Role_Customer)]
        public IActionResult PurchaseConsultation(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }

            // Logic to add consultation to the user's list
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userConsultation = new UserConsultation
            {
                ConsultationId = consultation.Id,
                UserId = userId
            };
            _context.UserConsultations.Add(userConsultation);
            _context.SaveChanges();

            return RedirectToAction("MyConsultations");
        }

        [Authorize(Roles = SD.Role_Customer)]
        [Route("Customer/User/MyCourse")]
        public IActionResult MyCourses()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var courses = _context.UserCourses
                                  .Where(uc => uc.UserId == userId)
                                  .Select(uc => uc.Course)
                                  .ToList();
            return View(courses);
        }

        [Authorize(Roles = SD.Role_Customer)]
        [Route("Customer/User/MyConsultation")]
        public IActionResult MyConsultations()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var consultations = _context.UserConsultations
                                        .Where(uc => uc.UserId == userId)
                                        .Select(uc => uc.Consultation)
                                        .ToList();
            return View(consultations);
        }


        [Route("Customer/User/CourseDetails/{id}")]
        public IActionResult CourseDetails(int id)
        {
            var course = _courseRepository.GetCourseById(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewBag.PaypalClientId = _configuration["PaypalSettings:ClientId"];
            ViewBag.PaypalSecret = _configuration["PaypalSettings:Secret"];
            ViewBag.PaypalUrl = _configuration["PaypalSettings:Url"];
            return View(course);
        }

        [Route("Customer/User/ConsultationDetails/{id}")]
        public IActionResult ConsultationDetails(int id)
        {
            var consultation = _consultationRepository.GetConsultationById(id);
            if (consultation == null)
            {
                return NotFound();
            }
            ViewBag.PaypalClientId = _configuration["PaypalSettings:ClientId"];
            ViewBag.PaypalSecret = _configuration["PaypalSettings:Secret"];
            ViewBag.PaypalUrl = _configuration["PaypalSettings:Url"];
            return View(consultation);
        }

        //[Authorize(Roles = SD.Role_Customer)]
       
        //public async Task<IActionResult> AddToCalendar(int id)
        //{
        //    var consultation = _consultationRepository.GetConsultationById(id);
        //    if (consultation == null)
        //    {
        //        return NotFound();
        //    }

        //    var googleAuth = _configuration.GetSection("GoogleAuth");
        //    string[] scopes = { CalendarService.Scope.Calendar };

        //    var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
        //        new ClientSecrets
        //        {
        //            ClientId = googleAuth["ClientId"],
        //            ClientSecret = googleAuth["ClientSecret"]
        //        },
        //        scopes,
        //        "user",
        //        CancellationToken.None);

        //    var service = new CalendarService(new BaseClientService.Initializer()
        //    {
        //        HttpClientInitializer = credential,
        //        ApplicationName = "SkillSphere",
        //    });

        //    var calendarEvent = new Event
        //    {
        //        Summary = consultation.Title,
        //        Description = consultation.Description,
        //        Start = new EventDateTime
        //        {
        //            DateTime = consultation.StartDate,
        //            TimeZone = "Asia/Kolkata"
        //        },
        //        End = new EventDateTime
        //        {
        //            DateTime = consultation.EndDate,
        //            TimeZone = "Asia/Kolkata"
        //        },
        //        Attendees = new List<EventAttendee>
        //    {
        //        new EventAttendee { Email = "attendee@example.com" }
        //    },
        //        ConferenceData = new ConferenceData
        //        {
        //            CreateRequest = new CreateConferenceRequest
        //            {
        //                RequestId = Guid.NewGuid().ToString(),
        //                ConferenceSolutionKey = new ConferenceSolutionKey
        //                {
        //                    Type = "hangoutsMeet"
        //                }
        //            }
        //        }
        //    };

        //    var request = service.Events.Insert(calendarEvent, "primary");
        //    request.ConferenceDataVersion = 1;
        //    var createdEvent = await request.ExecuteAsync();

        //    return Redirect(createdEvent.HtmlLink);
        //}

        //[Authorize(Roles = SD.Role_Customer)]
        //public async Task<IActionResult> AuthorizeGoogleCalendar(int id)
        //{
        //    var googleAuth = _configuration.GetSection("GoogleAuth");
        //    string[] scopes = { CalendarService.Scope.Calendar };

        //    var redirectUri = Url.Action("GoogleCalendarCallback", "User", new { id }, Request.Scheme);

        //    var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
        //        new ClientSecrets
        //        {
        //            ClientId = googleAuth["ClientId"],
        //            ClientSecret = googleAuth["ClientSecret"]
        //        },
        //        scopes,
        //        "user",
        //        CancellationToken.None,
        //        new FileDataStore("Google.Apis.Auth")
        //    );

        //    if (credential.Token.IsExpired(credential.Flow.Clock))
        //    {
        //        if (await credential.RefreshTokenAsync(CancellationToken.None))
        //        {
        //            // Redirect to the callback with the consultation ID
        //            return RedirectToAction("GoogleCalendarCallback", new { id });
        //        }
        //    }

        //    // If already authorized, redirect to callback immediately
        //    return RedirectToAction("GoogleCalendarCallback", new { id });
        //}



        //[Authorize(Roles = SD.Role_Customer)]
        //[Route("Customer/User/GoogleCalendarCallback")]
        //public async Task<IActionResult> GoogleCalendarCallback(int id)
        //{
        //    var consultation = _consultationRepository.GetConsultationById(id);
        //    if (consultation == null)
        //    {
        //        return NotFound();
        //    }

        //    var googleAuth = _configuration.GetSection("GoogleAuth");
        //    string[] scopes = { CalendarService.Scope.Calendar };

        //    var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
        //        new ClientSecrets
        //        {
        //            ClientId = googleAuth["ClientId"],
        //            ClientSecret = googleAuth["ClientSecret"]
        //        },
        //        scopes,

SkillSphere-.NET/SkillSphere/Areas/Customer/Views/User/ConsultationDetails.cshtml
@model SkillSphere.Models.Consultation

<script src="https://www.paypal.com/sdk/js?client-id=@(ViewBag.PaypalClientId)&currency=USD"></script>

<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        align-items: center;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .left-side {
        flex: 2;
        padding-right: 20px;
    }

    .right-side {
        flex: 1;
        max-width: 420px;
        padding-left: 20px;
        border-left: 1px solid #ddd;
    }

    .icon {
        margin-right: 8px;
    }

    .heading {
        font-size: 2rem;
        margin-bottom: 10px;
        display: flex;
        align-items: center;
    }

    .description {
        margin-bottom: 15px;
    }

    .info {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .price {
        font-size: 1.5rem;
        color: green;
        margin-bottom: 20px;
        display: flex;
        align-items: center;
    }

    .form-group {
        margin-bottom: 15px;
    }
</style>

<div class="container">
    <!-- Left Side -->
    <div class="left-side">
        <div class="heading">
            <i class="fas fa-book icon"></i>
            @Model.Title
        </div>
        <div class="description">
            <i class="fas fa-align-left icon"></i>
            @Model.Description
        </div>
        <div class="info">
            <i class="fas fa-clock icon"></i>
            Duration: @Model.Duration minutes
        </div>
        <div class="price">
            <i class="fas fa-dollar-sign icon"></i>
            Price: @Model.Price
        </div>
    </div>

    <!-- Right Side -->
    <div class="right-side">
        <h2 class="text-center mb-5">Complete your order</h2>
        <div class="form-group mb-3">
            <label class="form-label">Total Amount ($)</label>
            <input class="form-control" type="number" id="totalAmount" step='0.01' value="@Model.Price" />
        </div>
        <div id="notification-container"></div>
        <div id="paypal-button-container"></div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        paypal.Buttons({
            async createOrder() {
                const amount = document.getElementById('totalAmount').value;
                console.log("Amount to be paid:", amount);
                const response = await fetch("@Url.Action("CreateOrder", "Checkout")", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({ amount: amount })
                });

                const order = await response.json();
                console.log("Order response:", order);
                return order.id;
            },

            async onApprove(data) {
                console.log("Order ID:", data.orderID);
                const response = await fetch("@Url.Action("CompleteOrder", "Checkout")", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({ orderID: data.orderID })
                });

                const details = await response.json();
                console.log("Order completion response:", details);

                if (details.status === "success") {
                    window.location.href = "@Url.Action("PurchaseConsultation", "User", new { id = Model.Id })";
                } else {
                    alert("Payment failed. Please try again.");
                }
            },

            onError(err) {
                alert("An error occurred. Please try again.");
            }
        }).render('#paypal-button-container');
    });
</script>

SkillSphere-.NET/SkillSphere/Areas/Customer/Views/User/CourseDetails.cshtml
@model SkillSphere.Models.Course

@{
    string GetYouTubeThumbnail(string url)
    {
        if (string.IsNullOrEmpty(url))
        {
            return "/images/default-thumbnail.jpg";
        }

        var videoId = url.Split("v=")[1];
        return $"https://img.youtube.com/vi/{videoId}/0.jpg";
    }
}

<script src="https://www.paypal.com/sdk/js?client-id=@(ViewBag.PaypalClientId)&currency=USD"></script>

<style>
    .container {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .left-side {
        flex: 1;
        padding-right: 20px;
    }

    .right-side {
        flex: 1;
        max-width: 360px;
        padding-left: 20px;
    }

    .thumbnail {
        width: 60%;
        height: auto;
        border-radius: 10px;
        margin-bottom: 15px;
    }

    .icon {
        margin-right: 8px;
    }

    .heading {
        font-size: 1.5rem;
        margin-bottom: 10px;
        font-weight: 500;
        display: flex;
        align-items: center;
    }

    .description {
        margin-bottom: 15px;
        text-align: justify;
        display: flex;
        align-items: center;
    }

    .price {
        font-size: 1.5rem;
        color: green;
        margin-bottom: 20px;
        font-weight: 500;
        display: flex;
        align-items: center;
    }

    .form-group {
        margin-bottom: 15px;
    }
</style>

<div class="container">
    <!-- Left Side -->
    <div class="left-side">
        <div class="heading">
            <i class="fas fa-book icon"></i>
            @Model.Title
        </div>
        <img src="@GetYouTubeThumbnail(Model.VideoUrl)" alt="Course Thumbnail" class="thumbnail" />

        <div class="description">
            <i class="fas fa-align-left icon"></i>
            @Model.Description
        </div>
        <div class="price">
            <i class="fas fa-dollar-sign icon"></i>
            Price: @Model.Price
        </div>
    </div>

    <!-- Right Side -->
    <div class="right-side">
        <h2 class="text-left mb-5">Complete your order</h2>
        <div class="form-group mb-3">
            <label class="form-label">Total Amount ($)</label>
            <input class="form-control" type="number" id="totalAmount" step='0.01' value="@Model.Price" />
        </div>
        <div id="notification-container"></div>
        <div id="paypal-button-container"></div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        paypal.Buttons({
            async createOrder() {
                const amount = document.getElementById('totalAmount').value;
                console.log("Amount to be paid:", amount); // Debugging
                const response = await fetch("@Url.ActionLink("CreateOrder", "Checkout")", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({ amount: amount })
                });

                const order = await response.json();
                console.log("Order response:", order); // Debugging
                return order.id; // Ensure this returns the order ID
            },

            async onApprove(data) {
                console.log("Order ID:", data.orderID); // Debugging
                const response = await fetch("@Url.ActionLink("CompleteOrder", "Checkout")", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({ orderID: data.orderID })
                });

                const details = await response.json();
                console.log("Order completion response:", details); // Debugging

                if (details.status === "success") {
                    window.location.href = "@Url.Action("PurchaseCourse", "User", new { id = Model.Id })";
                } else {
                    alert("Payment failed. Please try again.");
                }
            },

            onError(err) {
                alert("An error occurred. Please try again.");
            }
        }).render('#paypal-button-container');
    });
</script>

SkillSphere-.NET/SkillSphere/Areas/Customer/Views/User/Index.cshtml
@model SkillSphere.Models.ViewModels.UserDashboardViewModel

@{
    string GetYouTubeThumbnail(string url)
    {
        if (string.IsNullOrEmpty(url))
        {
            return "/images/default-thumbnail.jpg";
        }

        var videoId = url.Split("v=")[1];
        return $"https://img.youtube.com/vi/{videoId}/0.jpg";
    }
}

<style>

    .banner {
        background-image: url('/images/Banner.jpg');
        background-size: cover;
        background-position: center;
        padding: 60px 20px;
        text-align: center;
        color: white;
        margin-bottom: 30px;
        margin-top: 30px;
        border-radius: 10px;
    }

        .banner h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
            color: white;
        }

        .banner h3 {
            font-size: 1.5rem;
            font-weight: 300;
            color: white;
        }

    .bannerB {
        background-color: steelblue;
        background-size: cover;
        background-position: center;
        padding: 60px 20px;
        text-align: center;
        color: white;
        margin-bottom: 30px;
        margin-top: 30px;
        border-radius: 10px;
    }

        .bannerB h1 {
            font-size: 1.5rem;
            margin-bottom: 10px;
            color: white;
        }

        .bannerB h3 {
            font-size: 1rem;
            font-weight: 300;
            color: white;
        }

    .card {
        border: 1px solid #ddd;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
        border-radius: 10px;
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }

        .card .card-body {
            padding: 15px;
        }

    .card-title {
        margin-bottom: 0.5rem;
    }

    .text-center {
        text-align: left;
    }

    .description {
        display: -webkit-box;
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
    }

        .description.collapsed {
            -webkit-line-clamp: unset;
            overflow: visible;
        }

    .show-more-btn {
        color: #007bff;
        cursor: pointer;
        font-size: 0.9rem;
        display: block;
        text-align: left;
        margin-top: 10px;
    }

    .icon-text {
        display: flex;
        align-items: left;
        justify-content: left;
        margin-top: 5px;
        color: #555;
    }

        .icon-text i {
            margin-right: 5px;
        }

</style>

<!-- Banner Section -->
<div class="banner">
    <h1>Smart Technical Learning Made Easy</h1>
    <h3>Buy courses, Consult with certified professionals</h3>
</div>

<h2>Available Courses</h2>
<br />
<div class="row pb-3" id="course">
    @foreach (var course in Model.Courses)
    {
        <div class="col-lg-2 col-md-3 col-sm-4 mb-4">
            <div class="card rounded h-100">
                <img src="@GetYouTubeThumbnail(course.VideoUrl)" class="card-img-top" alt="Course Thumbnail">
                <div class="card-body d-flex flex-column">
                    <div class="mb-auto">
                        <p class="card-title h6 text-dark opacity-75 text-uppercase text-left">@course.Title</p>
                        <p class="text-dark text-opacity-75 text-left description" id="description-@course.Id">@course.Description</p>
                        <span class="show-more-btn" onclick="toggleDescription(@course.Id)">Show More</span>
                    </div>
                    <div class="mt-auto">
                        <a asp-action="CourseDetails" asp-route-id="@course.Id" class="btn btn-primary bg-gradient border-0 form-control mt-4">
                            View More
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<h2>Available Workshops</h2>
<br />
<div class="row pb-3 ">
    @foreach (var consultation in Model.Consultations)
    {
        <div class="col-lg-2 col-md-3 col-sm-4 mb-4">
            <div class="card rounded h-100">
                <div class="card-body d-flex flex-column">
                    <div class="mb-auto">
                        <p class="card-title h6 text-dark opacity-75 text-uppercase text-left">@consultation.Title</p>
                        <!-- Duration with Icon -->
                        <div class="icon-text">
                            <i class="fas fa-clock"></i> @consultation.Duration mins
                        </div>

                        <!-- Date with Icon -->
                        <div class="icon-text">
                            <i class="fas fa-calendar-alt"></i> @consultation.StartDate.ToString("MMMM dd, yyyy")
                        </div>
                    </div>
                    <div class="mt-auto">
                        <a asp-action="ConsultationDetails" asp-route-id="@consultation.Id" class="btn btn-primary bg-gradient border-0 form-control mt-4">
                            View More
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<div class="bannerB">
    <h1>Smart Technical Learning Made Easy</h1>
    <h3>Buy courses, Consult with certified professionals</h3>
</div>

@section Scripts {
    <script>
        function toggleDescription(id) {
            var desc = document.getElementById('description-' + id);
            var btn = desc.nextElementSibling;

            if (desc.classList.contains('collapsed')) {
                desc.classList.remove('collapsed');
                btn.textContent = 'Show More';
            } else {
                desc.classList.add('collapsed');
                btn.textContent = 'Show Less';
            }
        }
    </script>
}

SkillSphere-.NET/SkillSphere/Areas/Customer/Views/User/MyConsultations.cshtml
@model IEnumerable<SkillSphere.Models.Consultation>

<h2>My Workshops</h2>
<div class="row">
    @foreach (var consultation in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">@consultation.Title</h5>
                    <p class="card-text">@consultation.Description</p>
                    <p class="card-text"><strong>Date & Time:</strong> @consultation.StartDate.ToString("f")</p>
                    <a href="@consultation.ExternalLink" class="btn btn-primary">Join</a>
                </div>
            </div>
        </div>
    }
</div>